### ISSUE TITLE
Capability of using <, <=, > in the requirements and their combination

### ISSUE THREAD

**Issue by wkentaro** [locusrobotics/catkin_virtualenv#12]
It seems that [this block](https://github.com/locusrobotics/catkin_virtualenv/blob/devel/catkin_virtualenv/src/catkin_virtualenv/requirements.py#L51) restricts the use of these operations, and with their combination (ex. `numpy>2,<=2.3`) looks difficult in [the merge](https://github.com/locusrobotics/catkin_virtualenv/blob/devel/catkin_virtualenv/src/catkin_virtualenv/requirements.py#L97).
(And also there can be a case of `-e git+https://XXXXXXX.git#egg=YYY`.)

Do you have plan and idea how to add them?

**Comment by wkentaro** [comment]
And I'd like to know what made you to use multiple requirements.txt files, and their combination:
https://github.com/locusrobotics/catkin_virtualenv/blob/21bd7dc220a9d2f464bcee47816df7ab8a55e19c/catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake#L59-L62

**Comment by paulbovbel** [comment]
What motivated me to use multiple requirements files was the idea that you could have:
  - package A implement library code that depends on external library B
  - package C <depend> on package A, and inherit package A's requirement of library B transparently

I agree, the current implementation is fairly limited. It would certainly be possible to add support for other combination of constraints here.
  - The combinatorial explosion would probably require taking a different approach than currently used
  - A cleaner way would probably be to rely on the ability of requirements files to recursively include requirements files, letting pip/setuptools handle the messy resolution.

**Comment by paulbovbel** [comment]
That was fairly easy, and I got to remove a bunch of code! https://github.com/locusrobotics/catkin_virtualenv/pull/15
