### ISSUE TITLE
allow use of [ and ] in requirements.txt

### ISSUE THREAD

**Issue by bbarnes52** [locusrobotics/catkin_virtualenv#18]
"RuntimeError: Invalid requirement name apache-beam[gcp]==2.4, must match ^[A-Za-z0-9_-]+$"

this is a valid requirement name, needs updating. also that regex seems like it should include "<" and ">" chars as well, as per https://github.com/locusrobotics/catkin_virtualenv/issues/12

**Comment by paulbovbel** [comment]
Regarding PR https://github.com/locusrobotics/catkin_virtualenv/pull/21/files, this is a fine addition.

However the regex you've updated is for the package name only.

Really a lot of the logic here should be refactored to use the packaging library https://github.com/pypa/packaging/blob/master/packaging/requirements.py, and generalized to support merging all the supported operators but that's been off my radar lately. PRs welcome!
