### ISSUE TITLE
Mixing non virtualenv packages with virtualenv packages

### ISSUE THREAD

**Issue by DerNeuburger** [locusrobotics/catkin_virtualenv#25]
Hey locusrobotics,

great job with creating a virtualenv wrapper. Saved me a lot of time rewriting a python 3 library!
Now I would like to mix my package with non virtualenv packages inside of the workspace. However when building the workspace, the catkin_virtualenv package gets built fine. Though other packages invoking "catkin_install_python" cannot be built throwing:
```
<my_package> loaded catkin_virtualenv, but never invoked 'catkin_generate_virtualenv'
CMakeLists.txt:29 (catkin_install_python)
```
It seems to be the problem, that the catkin_install_python macro gets overwritten and obligates the creation of a virtualenv first, I guess. Maybe that is desired... Do you have any suggestions if and how I could solve that, without putting all of my other packages into their personal virtualenv just using the standard interpreter?

Thanks, DerNeuburger

**Comment by paulbovbel** [comment]
Looks like your CMake is leaking between packages - are you using catkin_make?

This is certainly something that can be fixed by creating a new macro rather than overriding catkin_install_python, which may have been a poor decision in retrospect.

An easier approach may be just to suggest you use a build tool that isolates package builds, i.e. https://catkin-tools.readthedocs.io/en/latest/

**Comment by paulbovbel** [comment]
Closing due to suggested workaround likely being effective.

**Comment by YXGuan** [comment]
Hi Paul @paulbovbel ,

I made the same mistake you mentioned above and it really backfires. Could you please elaborate on  how to " create a new macro" please?


```
-- ==> add_subdirectory(nmea_navsat_driver)
-- Could NOT find catkin_virtualenv (missing: catkin_virtualenv_DIR)
-- Could not find the required component 'catkin_virtualenv'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "catkin_virtualenv"
  with any of the following names:

    catkin_virtualenvConfig.cmake
    catkin_virtualenv-config.cmake

  Add the installation prefix of "catkin_virtualenv" to CMAKE_PREFIX_PATH or
  set "catkin_virtualenv_DIR" to a directory containing one of the above
  files.  If "catkin_virtualenv" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  nmea_navsat_driver/CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/yuxiang/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/yuxiang/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

```
FYI, [catkin_virtualenv](https://github.com/locusrobotics/catkin_virtualenv) is already installed on my local machine

Thank you in advance.

**Comment by paulbovbel** [comment]
@YXGuan, your problem is not related to this issue, please check ROS answers for basic support. You should be invoking find_package(... catkin_virtualenv) somewhere, and you're not.

**Comment by roger85213** [comment]
hi @paulbovbel  i have met the same question with [DerNeuburger] . Can you describe more clearly about  creating a new macro ?

**Comment by samuelba** [comment]
This is pretty annoying, would be nice if the macro is not overwritten.
