### ISSUE TITLE
Startup Error after bloom packaging

### ISSUE THREAD

**Issue by psheltz** [locusrobotics/catkin_virtualenv#28]
I am using this package to wrap up some ROS utility classes and scripts. I included it into my Jenkins build-deploy pipeline and all goes well, including the deb file packaging. However, when I attempt

```
rosrun <package> <script name>
```

I get an import error when it tries to pull in `rospy`:
```
ImportError: cannot import name _remove_dead_weakref
```
This is a system library, so I wonder if rosrun is not activating the virtual environment correctly. Has anyone run into a similar issue when deploying with this tool?

**Update**: I ran my build-deploy process using the test_catkin_virtualenv package and had the same error output, but generated from a `rosunit` import.

**Comment by paulbovbel** [comment]
I'd be happy to help debug, could you provide a minimum working example to examine? This sounds less like an issue with rosrun, and more with the 'system or not' status of the underlying package.

You can check by creating an ordinary virtualenv with --system-site-packages, and see if that module is available.
