### ISSUE TITLE
Release request for 0.3.0

### ISSUE THREAD

**Issue by knorth55** [locusrobotics/catkin_virtualenv#39]
I made PR in https://github.com/locusrobotics/catkin_virtualenv-release/issues/1, but is there any plan to release `0.3.0`?

**Comment by paulbovbel** [comment]
Hi, I didn't see that, since the -release repo is basically just a metadata dump. I'm happy to release a mew version of catkin_virtualenv into the melodic rosdistro.

**Comment by knorth55** [comment]
Thank you for quick response!
Good! I'm looking for the new release :)
