### ISSUE TITLE
New kinetic release?

### ISSUE THREAD

**Issue by gavanderhoorn** [locusrobotics/catkin_virtualenv#44]
#39 asked for `0.3.0` and that got into Melodic.

Would it be possible to get a new release into Kinetic as well?

Perhaps even `0.4.0`?

**Comment by paulbovbel** [comment]
Wow, pre-release tests are cool! It passed, so happy to release for kinetic, even though I had stopped maintaining it some time back.

I also unhooked catkin_virtualenv from our internal CI, so the package versions shouldn't jump quite as much anymore...

**Comment by gavanderhoorn** [comment]
Awesome :+1: 

thanks.

**Comment by gavanderhoorn** [comment]
@paulbovbel: did you release into Kinetic as well? :)

I can only find a PR for Melodic: https://github.com/ros/rosdistro/pull/21515.

**Comment by paulbovbel** [comment]
Whoops, will fix

**Comment by paulbovbel** [comment]
Done https://github.com/ros/rosdistro/pull/21543

**Comment by gavanderhoorn** [comment]
Awesome again ;)

thanks.

**Comment by knorth55** [comment]
can you release `0.5.1` into kinetic, too?
it is only released in `melodic`.
