### ISSUE TITLE
Release catkin_virtualenv into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [locusrobotics/catkin_virtualenv#53]
Would you mind releasing `catkin_virtualenv` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 13 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by k-okada** [comment]
hi, at least, we need https://github.com/locusrobotics/catkin_virtualenv/pull/64 to execute with python3

**Comment by paulbovbel** [comment]
Thanks @k-okada, but I fixed it elsewhere. The code currently on `master` should work fine in python3. I'll try to setup a focal/noetic environment and give it a whirl sometime soon, but if you're anxious for a binary release, I'll take your word for confirmation and bloom!

**Comment by k-okada** [comment]
@paulbovbel thanks, i have tested on our repository and it seems so far so good to me.

**Comment by k-okada** [comment]
@paulbovbel kindly ping for bloom release on noetic

**Comment by paulbovbel** [comment]
Done! https://github.com/ros/rosdistro/pull/25807
