### ISSUE TITLE
Interaction/integration with pkgs that have setup.py?

### ISSUE THREAD

**Issue by gavanderhoorn** [locusrobotics/catkin_virtualenv#6]
I'm not a Python expert, but I'm looking to use `catkin_virtualenv` to distribute a Python-based tool - with quite some dependencies not available as a Debian (or other) package - as a catkin pkg.

This pkg has a `setup.py` which installs two modules and a nr of scripts (entrypoints).

Is there a way for `catkin_virtualenv` to use it, or would I have to recreate what it does in the added `CMakeLists.txt`?

**Comment by paulbovbel** [comment]
catkin_virtualenv overrides the catkin function `catkin_install_python` to create virtualenv loaders for your python scripts.

I don't have a way to pick up from setup.py's `entry_points:console_scripts` and do the same, though I imagine it's possible.

**Comment by gavanderhoorn** [comment]
So if I understand you correctly the recommended approach right now would be to use the provided `catkin_virtualenv` and the regular `catkin_python_*` CMake functions/macros to get the files and dirs copied to their proper destinations?

**Comment by paulbovbel** [comment]
correct, you can use it to install global or local script as per usual. I was actually surprised that catkin supports console_scripts at all, as <http://docs.ros.org/api/catkin/html/howto/format2/installing_python.html> doesn't mention it, but it's used heavily in ros_comm <https://github.com/ros/ros_comm/blob/lunar-devel/tools/roslaunch/setup.py> to install 'global' scripts such as roslaunch.

The same is accomplished via

```
catkin_install_python(...
DESTINATION ${CATKIN_PACKAGE_GLOBAL_DESTINATION}
```

**Comment by paulbovbel** [comment]
Going to close this ticket. Let me know how it goes!
