### ISSUE TITLE
0.6 in Kinetic and Melodic?

### ISSUE THREAD

**Issue by gavanderhoorn** [locusrobotics/catkin_virtualenv#69]
Yes, those are 'old', but there are some of us still using them :)

Is there anything technical blocking a release of `0.6` into Kinetic and Melodic?

**Comment by paulbovbel** [comment]
Nothing on my part - happy to release them as I think you're the primary consumer. Could you verify that 0.6 works on those distributions for you? The travis tests pass, which makes me relatively confident they would.

**Comment by gavanderhoorn** [comment]
Just build it locally and used it with `haros_catkin` in Kinetic and Melodic. Also ran a pre-release for Melodic, which reports 16 tests with no failures.

**Comment by gavanderhoorn** [comment]
I've used `0.6` "extensively" now on Xenial+Kinetic and Bionic+Melodic for #70 and #71.

This is obviously not an exhaustive test (so don't call me at 3am when things don't work ;) ), but I believe a release of `0.6` for those versions of ROS should be possible.

**Comment by paulbovbel** [comment]
:crossed_fingers: 

https://github.com/ros/rosdistro/pull/26295
https://github.com/ros/rosdistro/pull/26296
https://github.com/ros/rosdistro/pull/26297

**Comment by gavanderhoorn** [comment]
Thanks :+1: 

now to hope this doesn't break anyone's pkgs ;)

**Comment by gavanderhoorn** [comment]
Kinetic `0.6` release was merged by Tully and just got a notification from the buildfarm that the build(s) have started turning green again.

Thanks @paulbovbel :+1:

**Comment by gavanderhoorn** [comment]
Too soon :( Melodic builds are still failing, both Debian and Ubuntu based ones.

Might actually need a two-phase approach (first install setuptools `>=44,<45` and *then* install `pip`).

**Comment by gavanderhoorn** [comment]
Closing as `0.6` has been released into all current versions of ROS.

Thanks again @paulbovbel :+1:
