### ISSUE TITLE
ros-noetic-catkin-virtualenv dependency issue

### ISSUE THREAD

**Issue by shkiss** [locusrobotics/catkin_virtualenv#73]
I'm not sure this is the right place to log this issue, but the release of noetic on ubuntu 20 can't resolve it's own dependencies.

`ros-noetic-catkin-virtualenv` depends on `python-virtualenv`, which is not found.

Perhaps it is just a typo from `python3-virtualenv`? Curiously, the package also depends on `virtualenv` (without `python-`, found), so perhaps this dependency is not required at all.

Error:
```
$ sudo apt install ros-noetic-catkin-virtualenv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 ros-noetic-catkin-virtualenv : Depends: python-virtualenv but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by paulbovbel** [comment]
Sorry, I'm currently chasing this upstream (https://github.com/ros/rosdistro/pull/26325).

The recent 0.6.1 release has had the depedencies corrected, though it may need a 0.6.2 to fix up this last thing.

My CI runners install `python-dev` fine in focal, but the ros_buildfarm ones do not...
