### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by rayvo50** [locusrobotics/catkin_virtualenv#79]
after reading all the documentation and spending a lot of time searching the web I still do not understand how to use this package. There is no launch file and no information on how to actually use this package. Any help is much appreciated, thanks!

**Comment by paulbovbel** [comment]
Hi @rayvo50, I think the README is fairly detailed, but you can also look at what other packages use catkin_virtualenv and how they do it:

![image](https://user-images.githubusercontent.com/1694370/163038504-52349183-87f1-4834-8515-eeb2d071ac25.png)
