### ISSUE TITLE
GPL copyleft with regards to this library

### ISSUE THREAD

**Issue by Doomerdinger** [locusrobotics/catkin_virtualenv#82]
It is my understanding that with a typical use case with a GPL library if code uses it, that code must also be GPL (roughly, I know it is a lot more complicated).
Given that this library is GPL, one could assume libraries that use it must be GPL as well.

However, an example use case cited by this library is [locusrobotics/aiorospy](https://github.com/locusrobotics/aiorospy), which is MIT even though it uses this library.

Is this in error? Is the GPL copyleft not applicable with the way this library is used by downstream packages - since it is a bit unusual?

If this is more relevent to the aiorospy repo, I can close this and make an issue there instead. Likewise for if I should post this on answers.ros instead.

[This](https://answers.ros.org/question/340978/can-i-use-catkin_virtualenv-to-help-release-a-non-gplv2-package-with-bloom/) question seems somewhat related to this one, but not quite the same I don't think.

**Comment by androiddrew** [comment]
@Doomerdinger  I think you are referring to the misconception of the "virality" of licenses. If you create a derived work off of `catkin_virtualenv` yeah you are pretty much stuck with using GPL terms yourself. That is "did you modify the source code of catkin_virtualenv for your own purposes?" If so, then you are obligated to provide those changes to "the users" of your derived work under the same terms.  It does not necessarily obligate you to make your changes public, but those users can't be limited by any of the protections the license grants them. So even if you have someone paying you for your GPL'd software they have the same rights as before like being able to freely download it, modify it etc.

Use of a GPL licensed dependency does not virally make anything it touches GPL'd software. The GNU Compiler is GPL, granted it does make an explicit exception for header files in its corpus that may be compiled into your binaries. Catkin virtualenv isn't being compiled into your code. It is creating a wrapper around a virtualenv it maintains. It is not modifying your work. If you distribute any part of catkin_virtualenv you have to provide the user with the same license and rights to modify that code (the wrapper in this case).  Open up an Android phone and you can find a laundry list of licenses for different parts of what you "the user" received.

Of course, I'm not a lawyer, but also you have ask yourself what is the likelihood that Locusrobotics is going to take you to court? Ultimately, these terms and licenses are all about dispute resolution.  🤷

**Comment by androiddrew** [comment]
So, I talked to a build expert from a company that basically manages it's own distro.  She had directed me to https://www.gnu.org/licenses/gpl-faq.en.html which not so conveniently spells out a lot of "what you can and cannot do" in various scenarios regarding the GPL. I summarized her take on it back in the original [ROS answers thread you referenced](https://answers.ros.org/question/340978/can-i-use-catkin_virtualenv-to-help-release-a-non-gplv2-package-with-bloom/#398499. 

You can use catkin_virtualenv though without importing it into your python code. It is a build dependency specified in your package.xml file, no different than using `debhelper` of some other GPL build dependency tool. Even if it is modifying your code, that is it's purpose, and it's output is not immediately subject to the GPL([called out in](https://www.gnu.org/licenses/gpl-faq.en.html#CanIUseGPLToolsForNF) . I did not do an exhaustive investigation into the tool's under the hood workings, but it is simply modifying shebang lines and copying code to a virtualenv. As far as I can tell it is not copying any code from itself into your package that was copyrighted using the GPL, which I think is where a lot of people start to get worried. If you do find that this is modifying the output with it's own GPL content LocusRobotics can specify that as an acceptation much like the GCC example I listed above.

**Comment by paulbovbel** [comment]
That's a fantastic explanation @androiddrew, thanks a lot for taking the type to put that together! I'm not a licensing expert but I came to similar conclusions (though with less certainty). catkin_virtualenv keeps the GPL license because of it's origins with https://github.com/spotify/dh-virtualenv, but as it's pretty squarely in the infrastructure/tooling category, I don't feel like it should interfere with anyone's internal code and commercial business, unless your business is ROS infrastructure :)
