### ISSUE TITLE
catkin_virtualenv is resolvable by rosdep but not installable

### ISSUE THREAD

**Issue by androiddrew** [locusrobotics/catkin_virtualenv#84]
I am trying to install catkin_virtualenv, it is listed as a ros package http://wiki.ros.org/catkin_virtualenv I can see that it resolves to using `rosdep` but I can't seem to install it.

```
~/workspace/tmp$ rosdep resolve catkin_virtualenv
#apt
ros-noetic-catkin-virtualenv
~/workspace/tmp$ rosdep install catkin_virtualenv

ERROR: Rosdep cannot find all required resources to answer your query
Missing resource catkin_virtualenv
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/toor/workspace/tmp/src
ROS path [2]=/opt/ros/noetic/share
```

**Comment by paulbovbel** [comment]
AFAIK `rosdep install package_name` tries to install the dependencies for that package name. I usually use the invocation: `rosdep install --from-paths workspace/src --ignore-src -y` on my workspace
